### ISSUE TITLE
Salt is reused

### ISSUE THREAD

**Issue by martenjacobs** [wstam88/node-red-contrib-bcrypt#4]
This node will generate the same output on multiple events. Looking at the code, it seems the salt is generated on node initialisation and is then used throughout the lifetime of the node. 

I believe this is a major security issue as it would cause every password hashed using this node to be using the same salt, defeating the entire purpose of the salt. 

I think the salt should be regenerated for every 'encrypt' request. The salt should not be generated for the 'verify' request (as the salt is included in the hash already).

**Comment by awneil** [comment]
@wstam88 - this issue seems still present?

**Comment by wstam88** [comment]
I must have missed the notification for this issue... I will fix this today along with some additional improvements.

**Comment by wstam88** [comment]
Fixed! I also added some other improvements while I was at it:

- Allow non string fields to be hashed and compared
- Allow to change the field the hash is assigned to
- Allow to change the field where the boolean for comparison is assigned to
- Allow to change if the output for failed comparison goes to a separate output
- Added help text under the fields
- Tweaked the appearance/icon/color of the node

If you have any other feedback please report.

Have a nice day :)

**Comment by awneil** [comment]
Thanks.

How does one apply the update to what's already installed?

EDIT: never mind; found it - in the Palette manager.

**Comment by wstam88** [comment]
@awneil let me know if everything went well

**Comment by awneil** [comment]
Sorry for late reply - yes, it went fine.
